### PR TITLE
Update Ruby-based CI guidance

### PR DESCRIPTION
**Pull request by irisfaraway**
Deppbot has not been pushing updates for several months now. We've been using Dependabot on the waste carriers renewals project and have found this is a good substitute (with some configuration).

DependencyCI has merged into Tidelift and now follows a subscription model, so the features we used to use are now only available with a paid subscription. So for that reason I've removed it from the guidance alltogether.

### CODE REVIEW

**Comment by irisfaraway** [comment]
I also made some punctuation suggestions, but feel free to tell me to do these in a separate PR or just strip them out entirely!

**Comment by irisfaraway** [comment]
@Cruikshanks I'm blocked from merging this due to a markdown linting issue on a different file – should I make a separate PR to try to sort that out?

**Comment by Cruikshanks** [comment]
If you have the time that would be awesome @irisfaraway

**Comment by irisfaraway** [comment]
@Cruikshanks Done: https://github.com/DEFRA/dst-guides/pull/54

**Pull request merged**
